allowBuilds:
  '@prisma/engines': true
  core-js: set this to true or false
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
minimumReleaseAge: 0
minimumReleaseAgeExclude:
  - '@supabase/*'
