ALTER TABLE "ppmps" ADD COLUMN IF NOT EXISTS "documentUrl" TEXT;
ALTER TABLE "ppmps" ADD COLUMN IF NOT EXISTS "documentName" TEXT;
ALTER TABLE "ppmps" ADD COLUMN IF NOT EXISTS "documentSize" INTEGER;
ALTER TABLE "ppmps" ADD COLUMN IF NOT EXISTS "documentUploadedAt" TIMESTAMP(3);
